sonar.projectKey=sample-app-jenkins-pipeline
sonar.projectName=Sample App Jenkins Pipeline
sonar.projectVersion=1.0

# Scan the current project directory
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude files/folders that don't need analysis
sonar.exclusions=**/.git/**,**/helm/**,**/node_modules/**,**/*.md
