replicaCount: 1

image:
  repository: snehaldesai241/sample-app-jenkins-pipeline
  tag: "11"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80